wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695194291.337098
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.15.8
      8:
      - 3
      - 5
      10:
      - 3
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 700
batch_size:
  desc: null
  value: 64
